# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 继小鹏的博客
email: 1319639755@qq.com
author: Jipeng Huang
url: "http://www.huanghanlian.com"
description: Actually, less is more!
baseurl: "" # the subpath of your site, e.g. /blog

safe: false




twitter_username: jekyllrb
github_username:  jekyll





# Build settings
markdown: kramdown
kramdown:
  input:  GFM
  enable_coderay: true


# use_coderay: true



paginate: 10
paginate_path: "page:num"
gems: [jekyll-paginate]

# Comment setting
comments :
  provider : duoshuo
  duoshuo :
    short_name : huanghuanlian